apiVersion: v1
kind: Pod
metadata:
  name: pod-hostpath
  namespace: audit-zone
spec:
  volumes:
    - name: host-etc
      hostPath:
        path: /etc
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - name: host-etc
          mountPath: /host-etc
