apiVersion: v1
kind: Pod
metadata:
  name: pod-secure-no-hostpath
  namespace: audit-zone
spec:
  securityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  volumes:
    - name: tmp
      emptyDir: {}
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - name: tmp
          mountPath: /tmp
      securityContext:
        allowPrivilegeEscalation: false
        runAsNonRoot: true
        readOnlyRootFilesystem: true
        capabilities:
          drop: ["ALL"]
